### ISSUE TITLE
gigascience revision checklist

### ISSUE THREAD

**Issue by jesstytam** [jessicatytam/honours#53]
**Data**
- reply 14: check iucn red list status
  - [ ] fill in species with Near Threatened categories (~300?)
  - [ ] re-run mcmcglmm

**Text**
- [ ] reply 17: clarify how the titles were skimmed in the results
- [ ] reply 19 & 20: 'We think the rewording here is a better reflection of the results but that the sentence needs clarifying a bit - e.g. the part starting with however sounds like it is meant to contradict the previous sentence. Some suggested wording (assuming we have understood the meaning):
"These findings could jointly indicate that larger mammals that are less endangered could be attracting more research attention than smaller mammals that are severely endangered. Since taxa with larger mammals, such as the big cats and African megafauna, are typically considered more charismatic [8,42], larger mammals may receive more research interest than smaller mammals, regardless of whether or not they are threatened"'

**Comment by itchyshin** [comment]
@jessicatytam - thanks for doing this - once you return from the retreat, we can meet regularly to finish it off
